# Dependencies
markdown : kramdown
# Permalinks
permalink:        pretty

# Setup
title:            'AI for&#10;Social Good'
tagline:          'IJCAI 2020 Workshop'
description:      'IJCAI 2020 Workshop'
url:              "http://aiforgood2020.github.io"
baseurl:          "/"

paginate:         5

# Custom vars
version:          2.1.0
