# Dependencies
markdown : kramdown
# Permalinks
permalink:        pretty

# Setup
title:            'AI for&#10;Social Good'
tagline:          'Harvard CRCS Workshop'
description:      'Harvard CRCS Workshop'
url:              "http://aiforgood2020.github.io"
baseurl:          "/"

paginate:         5

# Custom vars
version:          2.1.0
